apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: NodePort  # Changed from default ClusterIP to NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Optional: specify a node port (ensure it is in the range 30000-32767)
  selector:
    app: guestbook-ui
